server:
  port: 8044

---

spring:
  profiles: test
  redis:
    host: 47.97.198.182
    port: 16379
    password: tauros@fitness
    timeout: 60000

log:
  mode: test
  level: INFO
  dir: ~/kaleido/aron/logs