server:
  port: 8044

spring:
  application:
    name: kaleido-aron

---

spring:
  profiles: dev
  redis:
    host: 47.97.198.182
    port: 16379
    password: tauros@fitness
    timeout: 60000
  cloud:
    nacos:
      discovery:
        server-addr: 47.97.198.182:8848
        ip: 127.0.0.1

log:
  mode: test
  level: INFO
  dir: ~/kaleido/aron/logs

dubbo:
  application:
    name: kaleido-aron
  registry:
    group: kaleido-aron
    version: 1.0.0
    address: nacos://47.97.198.182:8848
  protocol:
    host: 127.0.0.1
    name: dubbo
    port: 20880
  consumer:
    timeout: 3000

---

spring:
  profiles: test
  redis:
    host: 127.0.0.1
    port: 16379
    password: tauros@fitness
    timeout: 60000
  cloud:
    nacos:
      discovery:
        server-addr: 47.97.198.182:8848
        ip: 47.97.198.182

log:
  mode: test
  level: INFO
  dir: /root/app/kaleido-aron/logs

dubbo:
  application:
    name: kaleido-aron
  registry:
    group: kaleido-aron
    version: 1.0.0
    address: nacos://47.97.198.182:8848
  protocol:
    host: 127.0.0.1
    name: dubbo
    port: 20880
  consumer:
    timeout: 3000
